site_name: Python3_Docs_Note
pages:
    - Home: index.md
    - Python基础: 
        - '1. 数字': 'Numbers.md'
        - '2. 字符串': 'Strings.md'
        - '3. 列表': 'Lists.md'
        - '4. 元组': 'Tuple.md'
        - '5. 集合': 'Set.md'
        - '6. 字典': 'Dict.md'
        - '7. 逻辑运算符': 'Logical.md'
        - '8. 函数': 'Function.md'
        - '9. 类': 'Class.md'
        - '10. 文件': 'File.md'
        - '11. 异常': 'Abnormal.md'
        - '12. 正则': 'Regular.md'
    - Python中级:
        - 'Mysql': 'Mysql.md'
        
        
    - Django: 
        - '1. 创建Django项目': 'Create_project.md'
        - '2. 创建视图': 'Create_project_views.md'
        - '3. URL路由': 'Create_project_routing.md'
        - '4. Templates': 'Templates.md'
        - 'Orm基础': 'Orm.md'
        - 'Orm增删改查': 'Orm_add_delete_update_search.md'
        - 'Orm聚合查询': 'Orm_Aggregate_query.md'
    
    - Tornado: Tornado.md

    - Sublime Text3:
        - 'Package Control': 'PackageControl.md'
        - '解决Sublime的PackageControl被墙': 'SublimeText3PackageControl.md'
        - '自动保存配置': 'Autosave.md'
        - '手动安装Predawn主题': 'Predawn.md'
        - 'SublimeCodeIntel代码自动提示/补全插件': 'SublimeCodeIntel.md'
        - 'SublimeText3 Command+b运行python配置': 'command+b.md'

        
theme:
    name: readthedocs