site_name: Python3_Docs_Note
pages:
    - Python基础: 
        - 'Writing your docs': 'writing-your-docs.md'
        - '数字':'Numbers.md'
        - '字符串':'Strings.md'
        - '列表':'Lists.md'
        
    - Python中级:
        - 'Mysql':'Mysql.md'
        
    - Django: django.md
    
    - Tornado: tornado.md
    
    - User Guide:
        - 'Writing your docs': 'writing-your-docs.md'
        
    - About:
        - 'License': 'license.md'
    
theme:
    name: readthedocs
