site_name: Python3_Docs_Note
pages:
    - Home: index.md
    - Python基础: 
        - '1. 数字': 'Numbers.md'
        - '2. 字符串': 'Strings.md'
        - '3. 列表': 'Lists.md'
        - '4. 元组': 'Tuple.md'
        - '5. 集合': 'Set.md'
        - '6. 字典': 'Dict.md'
        - '7. 逻辑运算符': 'Logical.md'
        - '8. 函数': 'Function.md'
        - '9. 类': 'Class.md'
        - '10. 文件': 'File.md'
        - '11. 异常': 'Abnormal.md'
        - '12. 正则': 'Regular.md'
    - Python中级:
        - 'Mysql': 'Mysql.md'
        
        
    - Django: 
        - 'Templates': 'Templates.md'
        - 'Orm基础': 'Orm.md'
        - 'Orm增删改查': 'Orm_add_delete_update_search.md'
        - 'Orm聚合查询': 'Orm_Aggregate_query.md'
    
    - Tornado: Tornado.md

    - Sublime Text3:
        - '自动保存配置': 'Autosave.md'
        - 'Package Control': 'PackageControl.md'
        - '手动安装Predawn主题': 'Predawn.md'
        - 'SublimeText3Python开发环境配置': 'SublimetextPython.md'
theme:
    name: readthedocs