site_name: Python3_Docs_Note
pages:
    - Python基础: 
        - 'Python data type'：'datatype.md' 
        
    - Python中级:
        - 'Mysql':'Mysql.md'
        
    - Django: django.md
    
    - Tornado: tornado.md
    
    - User Guide:
        - 'Writing your docs': 'writing-your-docs.md'
        - 'Styling your docs': 'styling-your-docs.md'
        
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
    
theme:
    name: readthedocs
