site_name: Python3_Docs_Note
pages:
    - Python基础: 
        - '1. 数字': 'Numbers.md'
        - '2. 字符串': 'Strings.md'
        - '3. 列表': 'Lists.md'
        - '4. 元组': 'Tuple.md'

    - Python中级:
        - 'Mysql': 'Mysql.md'
        
    - Django: django.md
    
    - Tornado: tornado.md
theme:
    name: readthedocs
